/**
 * Serves the gallery under a path prefix as well as at a domain root.
 *
 * WHY THIS FILE EXISTS
 *
 * The site is deployed twice over:
 *
 *   https://arwynspace.mrarwyn.workers.dev/        — at the root
 *   https://arwyn.party/bitcoinart/                — under a prefix
 *
 * `arwyn.party/*` is already routed to a different Worker, so this Worker takes
 * only `arwyn.party/bitcoinart*`. Cloudflare resolves overlapping routes by
 * specificity, so the longer pattern wins for those paths and the rest of
 * arwyn.party is untouched.
 *
 * Static assets are matched BEFORE this script runs (the default; `run_worker_first`
 * is deliberately not set — see below). So at the root, `/app.css` is served
 * directly by the asset router and this code never executes. It runs only for paths
 * that match no asset, which is exactly the prefixed ones: `/bitcoinart/app.css` is
 * not an asset, so the request lands here and gets the prefix stripped.
 *
 * THE TRAILING SLASH IS LOAD-BEARING
 *
 * Every asset reference in the site is relative — `./app.css` in index.html,
 * `./data/holders.json` and `./api/holders` in app.js. That is what lets one build
 * serve from two different base paths without a rewrite step. But it means the base
 * path must end in a slash: from `/bitcoinart` the browser resolves `./app.css` to
 * `/app.css` (wrong, and on arwyn.party that is another Worker's territory), while
 * from `/bitcoinart/` it resolves to `/bitcoinart/app.css` (right). So a request
 * without the slash is redirected rather than served.
 *
 * WHY NOT run_worker_first
 *
 * Because `public/_headers` would stop applying. Cloudflare's docs are explicit
 * that custom headers are not attached to responses generated by Worker code, and
 * name `run_worker_first` as a case where you must set headers yourself. Leaving the
 * asset router in front means unprefixed requests keep their `_headers` rules with
 * no second copy of that config to drift out of sync.
 */

const PREFIX = "/bitcoinart";

export default {
  async fetch(request, env) {
    const url = new URL(request.url);

    // Bare prefix with no trailing slash: redirect, don't serve. See above.
    // 308 rather than 301/302 so the method is preserved and the redirect is
    // permanently cacheable.
    if (url.pathname === PREFIX) {
      url.pathname = `${PREFIX}/`;
      return new Response(null, { status: 308, headers: { Location: url.toString() } });
    }

    if (url.pathname.startsWith(`${PREFIX}/`)) {
      const target = new URL(url);
      // Strip the prefix. "/bitcoinart/" becomes "/", which the asset router
      // resolves to index.html.
      target.pathname = url.pathname.slice(PREFIX.length) || "/";
      return env.ASSETS.fetch(new Request(target.toString(), request));
    }

    // Anything else: hand back to the asset router. Reached only when no asset
    // matched, so this is effectively the 404 path.
    return env.ASSETS.fetch(request);
  },
};
